### ISSUE TITLE
Importing XML fails, but zip folder works

### ISSUE THREAD

**Issue by DAflamingFOX** [wnbittle/praisenter#33]
As stated attempting to import a raw xml file will throw an exception, but importing the same file in a zip folder works fine.

Here is the file:
[WE_Bible_English_NLT.zip](https://github.com/wnbittle/praisenter/files/11185703/WE_Bible_English_NLT.zip)

```
java.util.concurrent.CompletionException: java.lang.Exception: Failed to import path 'C:\Users\Media 2\Desktop\WE_Bible_English_NLT.xml' it does not match any supported format of media, bible, song, or slide.
	at org.praisenter.data.workspace.WorkspaceManager.lambda$importData$9(WorkspaceManager.java:364)
	at org.praisenter.async.AsyncHelper.lambda$onJavaFXThreadAndWait$5(AsyncHelper.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at org.praisenter.async.AsyncHelper.lambda$onJavaFXThreadAndWait$2(AsyncHelper.java:58)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Failed to import path 'C:\Users\Media 2\Desktop\WE_Bible_English_NLT.xml' it does not match any supported format of media, bible, song, or slide.
	... 13 more
```

**Comment by wnbittle** [comment]
Thanks for the bug report.  I've made a change and new builds should be ready.  Can you verify the fix works for you?

**Comment by DAflamingFOX** [comment]
Yep seems to work on my machine, thanks!
